# Project-wide Gradle settings.
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17


# AndroidX package structure to make it clearer which packages are part of the Android SDK
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Use non-transitive R classes to speed up builds and reduce APK size
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
